# Generated by Django 5.2 on 2025-04-21 14:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackbase', '0002_question_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.AddField(
            model_name='question',
            name='data_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
